// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMqp-yDsu7TUOHllTMKlJEFt3KsM_oj0',
    appId: '1:1009643680241:web:8a0373bdad8423b14e1450',
    messagingSenderId: '1009643680241',
    projectId: 'shop-future',
    authDomain: 'shop-future.firebaseapp.com',
    storageBucket: 'shop-future.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBquHyc_2mXWnCc73YhgSwS8fg2hqI96pI',
    appId: '1:1009643680241:android:1ed0cd9bb63a07e04e1450',
    messagingSenderId: '1009643680241',
    projectId: 'shop-future',
    storageBucket: 'shop-future.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEAO9I6WLpmJBL5ZBptznveXIEd2-MMo',
    appId: '1:1009643680241:ios:dc5c634e01c0b4444e1450',
    messagingSenderId: '1009643680241',
    projectId: 'shop-future',
    storageBucket: 'shop-future.firebasestorage.app',
    iosBundleId: 'com.example.premiumStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEAO9I6WLpmJBL5ZBptznveXIEd2-MMo',
    appId: '1:1009643680241:ios:dc5c634e01c0b4444e1450',
    messagingSenderId: '1009643680241',
    projectId: 'shop-future',
    storageBucket: 'shop-future.firebasestorage.app',
    iosBundleId: 'com.example.premiumStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlMqp-yDsu7TUOHllTMKlJEFt3KsM_oj0',
    appId: '1:1009643680241:web:811b66fbdab689334e1450',
    messagingSenderId: '1009643680241',
    projectId: 'shop-future',
    authDomain: 'shop-future.firebaseapp.com',
    storageBucket: 'shop-future.firebasestorage.app',
  );
}
